version: "3.3"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always

    networks:
      - traefik

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      # Frontend
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`portainer.hercules.codes`)"
      - "traefik.http.routers.frontend.tls.certresolver=le"

networks:
  traefik:
    name: traefik
    external: true

volumes:
  portainer_data:
